name: PR on Push & Release on Merge

on:
  push:
    branches:
      - development

  pull_request:
    branches: [main]
    types: [closed]

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

    # Other PR job steps

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [16]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - run: npm install
      - run: npm run build

  release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: [pull-request, build]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: my-package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
