name: Auto Pull Request and Auto Merge

on:
  push:
    branches:
      - development

  pull_request:
    branches: [main]
    types: [closed]

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install Dependencies
        run: npm install

      - run: npm run build

  merge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: [pull-request, build]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Merge Pull Request
        run: |
          git merge --no-ff ${{ github.event.pull_request.head.sha }} -m "Merge pull request #${{ github.event.pull_request.number }}"

      - name: Tag Release
        run: |
          # Assuming you have a version in your package.json
          version=$(node -p -e "require('./package.json').version")
          git tag -a "v${version}" -m "Release v${version}"
          git push origin "v${version}"
      - name: Cleanup
        run: |
          # Delete the feature branch after merging
          git branch -d "${{ github.head_ref }}"
