name: PR on Push & Version on Merge

on:
  push:
    branches:
      - development

  pull_request:
    branches: [main]
    types: [closed]

jobs:
  pull-request:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v2

      - name: Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "development"
          destination_branch: "main"
          pr_title: "Development to Main"
          pr_allow_empty: true
        env:
          MY_PAT: ${{ secrets.MY_PAT }}

  version:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: pull-request

    steps:
      - uses: actions/checkout@v2

      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Release
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: my-package
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
